### ISSUE TITLE
Additional feedback on the "Low-overhead image file format" proposal for HEIF

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#108]
#104 provides feedback on the `mini` proposal. I've checked over that discussion, and I there are a couple of additional items. (Possibly most of #104 proposals were incorporated into the MPEG 147 version).

In section O.3.3, the semantics for `small_dimensions_flag` appear reversed. That is, 0 indicates the size is 15 bits, and 1 indicates the size is 7 bits.

Same issue for `few_metadata_bytes_flag`. 0 indicates the size is 20 bits, 1 indicates 10 bits.

Same issue for `few_codec_config_bytes_flag`. 0 indicates the size is 12 bits, 1 indicates 3 bits.

Same issue for `few_item_data_bytes_flag`. 0 indicates the size is 28 bits, 1 indicates 15 bits.

With those changes, my reader is interoperable with the libavif experimental implementation, noting no coverage of HDR. 

More generally, I think this is a worth-while improvement. I could live without the HDR part, but its not a blocker.

**Comment by y-guyon** [comment]
> #104 provides feedback on the `mini` proposal. I've checked over that discussion, and I there are a couple of additional items. (Possibly most of #104 proposals were incorporated into the MPEG 147 version).

Thank you for reviewing. We also have further corrections that may be presented to [MPEG 148](https://www.mpeg.org/meetings/mpeg-148/).

> In section O.3.3, the semantics for `small_dimensions_flag` appear reversed. That is, 0 indicates the size is 15 bits, and 1 indicates the size is 7 bits.
> 
> Same issue for `few_metadata_bytes_flag`. 0 indicates the size is 20 bits, 1 indicates 10 bits.
> 
> Same issue for `few_codec_config_bytes_flag`. 0 indicates the size is 12 bits, 1 indicates 3 bits.
> 
> Same issue for `few_item_data_bytes_flag`. 0 indicates the size is 28 bits, 1 indicates 15 bits.

Good catch, I am adding this discrepancy to the next input document as a rename suggestion.

> With those changes, my reader is interoperable with the libavif experimental implementation, noting no coverage of HDR.
> 
> More generally, I think this is a worth-while improvement. I could live without the HDR part, but its not a blocker.

HDR was added in libavif in https://github.com/AOMediaCodec/libavif/pull/2440. You meant your reader has no HDR coverage?

**Comment by bradh** [comment]
> HDR was added in libavif in [AOMediaCodec/libavif#2440](https://github.com/AOMediaCodec/libavif/pull/2440). You meant your reader has no HDR coverage?

libheif doesn't do HDR yet. I'll make sure my implementation handles the parsing, but the data will be ignored for now.

IMO, its not completely clear that the added complexity for HDR is justified for the kind of applications where  low-overhead `mini` would be used. `mini` saves a few hundred bytes over a full `meta`, and that just disappears in the noise when there is alpha, tone mapping, etc. I think it makes sense for icons, and for things like zoomable maps (e.g. openstreetmap) as a replacement for PNG. I just don't see as much demand for HDR icons.

**Comment by leo-barnes** [comment]
> I just don't see as much demand for HDR icons. That said, I assume its important to someone, and I can accept that. Its only a few bits for applications that choose not to use it, and the only downside is reader complexity.

It's also beneficial if you want your medium/small thumbs to have the same HDR look as your big images. Even though the savings are not massive for larger images, we're still talking ~200 bytes per file. In aggregate for all images on the web, that ends up being a lot of data that could be saved, or a lot of traffic that could be avoided.

**Comment by bradh** [comment]
Additional issue: the format appears to require every channel to have the same bit depth. I think that is always true for AV1 and probably for VVC. However it may not be true for AVC, HEVC, EVC, JPEG 2000 and uncompressed (yeah, OK...). It might not be true for the alpha overlay either, where 1 bit might be ideal for some cases.

Can we use the remaining bits to repeat / extend the current bit depth structure?  So if the flag(s) are not set then it uses the single bit depth for everything, but flags might mean the first bit depth is just luma, and that chroma and alpha depths also need to be parsed out.

I don't have a clean design that covers chroma bit depth and alpha bit depth, but because of how `float_flag` and `high_bit_depth_flag` are cross-cutting, but hopefully this provides a starting point.

**Comment by leo-barnes** [comment]
> Additional issue: the format appears to require every channel to have the same bit depth. I think that is always true for AV1 and probably for VVC. However it may not be true for AVC, HEVC, EVC, JPEG 2000 and uncompressed (yeah, OK...). It might not be true for the alpha overlay either, where 1 bit might be ideal for some cases.

We have debated whether we should support having different bit-depths for each channel multiple times. Each time we've come to the conclusion that:
1. It's currently not used _anywhere_ in HEIF that we're aware.
2. It's an edge case that might be useful in some cases but is not critical. You _can_ work around it by just using the same bit-depth for all channels.

Neither of these points makes it really fit the end-goal: 
Reduce overhead for common, simple and/or small files, with the prime goal being the web since this is where it matters the most.

We can always create an updated version in the future if having different bit-depths for each channel turns out to be common, but at the moment I would say it's out of scope.

**Comment by bradh** [comment]
> We can always create an updated version in the future if having different bit-depths for each channel turns out to be common, but at the moment I would say it's out of scope.

OK. I think it would be worth making this explicit in the introduction to Annex O (e.g. the O.1 General section, between the first and second paragraphs).  Perhaps something like:

> MinimizedImageBox is suited to common use-cases, but has inherent limitations over the larger and more flexible MetaBox. These limitations include:
> - A single image file, with optional alpha and HDR auxiliary information, and optional XMP and EXIF metadata
> - A common bit depth for all channels (including alpha, if present)
> - A small number of transformative properties (e.g. mirroring or rotation are possible, but scaling is not possible).
> - No support for encryption
> - No support for user-defined properties

**Comment by farindk** [comment]
I agree that different bit-depths for luma and chroma channels appears to be not used anywhere.
However, forcing alpha to high bit-depths for HDR images seems to contradict the goal of having a small file size.

How about such a logic:
- if the color bit depth is 8, alpha implicitly is also 8 (`high_bit_depth_flag` not set)
- if the color bit depth is >8, alpha bit depth is signaled (maybe as `alpha_depth-8`)

**Comment by y-guyon** [comment]
> I think it would be worth making this explicit

In the latest draft, some wording is present in a paragraph and in a note, mentioning that SlimHEIF is for small and simple image files.  
One can check the `MinimizedImageBox` syntax for supported features. Listing supported or unsupported features exhaustively would be quite long, and a partial list could be misleading.

> I agree that different bit-depths for luma and chroma channels appears to be not used anywhere. However, forcing alpha to high bit-depths for HDR images seems to contradict the goal of having a small file size.

I am not certain that 10-bit alpha samples compress worse than 8-bit ones.  
Moreover the codec could store 8-bit samples but expose 10-bit values to the container. This would be a cheap upscale operation if the compression gains are worth it (and applicable to other channels than alpha).
