### ISSUE TITLE
padding_flag in leva should be deprecated?

### ISSUE THREAD

**Issue by dwsinger** [MPEGGroup/FileFormat#11]
As noted in m50898, "`leva`" description of padding flag is wrong. It states:

> When `padding_flag` is equal to 1 this indicates that a conforming fraction can be formed by concatenating any positive integer number of levels within a fraction and padding the last `MediaDataBox` by zero bytes up to the full size that is indicated in the header of the last `MediaDataBox`. For example, `padding_flag` can be set equal to 1 when the following conditions are true: 
> • Each fraction contains two or more AVC, SVC, or MVC [ISO/IEC 14496-15] tracks of the same video bitstream. 
> • The samples for each track of a fraction are contiguous and in decoding order in a MediaDataBox. 
> • The samples of the first AVC, SVC, or MVC level contain extractor NAL units for including the video coding NAL units from the other levels of the same fraction. 
> 

However, the padded level is not compliant, since its samples will typically be a bag of "0" bytes. In the given NALU-based example, if the sample size is not a multiple of lengthSizeMinusOne, this will no longer be a valid sample (size mismatch).
Therefore the promise of " a conforming fraction can be formed by concatenating any positive integer number of levels within a fraction and padding the last `MediaDataBox` by zero bytes up to the full size that is indicated in the header of the last `MediaDataBox`. " is simply wrong: this is not a conforming fraction and it is likely that a AVCFF conformance checker will reject the file.
We therefore wonder if `padding_flag` should not be simply deprecated.

**Comment by dwsinger** [comment]
also

The padding_flag in 'leva' indicates that padding the mdat with 0 would result in a valid file (conformant fraction). The specification gives the following example:

> • Each fraction contains two or more AVC, SVC, or MVC [ISO/IEC 14496-15] tracks of the same video bitstream. 
> • The samples for each track of a fraction are contiguous and in decoding order in a MediaDataBox. 
> • The samples of the first AVC, SVC, or MVC level contain extractor NAL units for including the video coding NAL units from the other levels of the same fraction. 
> 

Extractors for AVC/SVC/MVC shall point to the beginning of a NAL unit size field. However, if the data_offset used in the extractor is not 0 (not the beginning of the sample), it is very likely to point to something that is not the start of a NAL unit size field in the 0-padded sample. Shouldn't we clarify this :
" The samples of the first AVC, SVC, or MVC level contain extractor NAL units for including the video coding NAL units from the other levels of the same fraction, and these extractors always point to the beginning of the extracted sample (data_offset=0)."

**Comment by mhannuksela** [comment]
The use case was described in MPEG M18464 (October 2010) as follows. Note that there are also illustrative figures in the contribution (which I could not paste here). 

> The media bitstream is divided into base media data and enhancement media data. The base media data represents a decodable base-quality version of the media data. It can be the temporal base layer (with temporal_id equal to 0) of an AVC, SVC, or MVC stream, or the MGS base layer (with quality_id equal to 0) of an SVC stream. The enhancement media data can be a temporal enhancement layer (with temporal_id greater than 0) or an MGS enhancement layer of an SVC stream (with quality_id greater than 0).
> 
> In this document, a movie fragment refers to a Movie Fragment box and an immediately following mdat box containing the media samples described by the Movie Fragment box. In the example movie fragment structure (see the figure below), a sample in the base media track represents an SVC access unit and consists of two parts: the base layer dependency representation and an extractor NAL unit. The extractor NAL unit points to the enhancement media track, which includes the NAL units for the enhancement layer(s). A sample in the enhancement media track also represents an SVC access unit and consists of two parts: an extractor NAL unit and the enhancement media data. The extractor NAL unit refers to the base layer dependency representation included in the base media track. 
>  
> A DASH client retrieves a movie fragment in two parts. It first gets a part which contains at least the Movie Fragment (moof) box and typically some of the media data of the base layer/view. It parses the Movie Fragment box, determines which tracks it is capable of receiving, and issues an HTTP GET request for another part of the movie fragment containing the media data for the desired layers/views. In particular, the DASH client can use the base_data_offset field in the Track Fragment Header box to determine the starting byte offset of the enhancement layer data within the mdat box. In many practical cases, it is advisable to either request the movie fragment entirely, or request only the base layer data and omit the enhancement layer data entirely. However, as the media data within each layer appears in decoding order within the mdat box, any integer number of samples of the enhancement layer data can be requested, while the received movie fragment and created file remain conforming. The DASH client may use the sample_size fields to determine which enhancement layer samples are requested. Note also that the proposal is not limited to one track of enhancement layer data, but there can be more than one hierarchically arranged enhancement layer tracks.
> 
> When writing the received movie fragment into a file, the DASH client first initializes the mdat box with value 0 so that the size field of the mdat box header is respected. The DASH client then writes the received media data of the movie fragment on top of the initialized byte range. The NAL units that are not received are therefore replaced by value 0, which is interpreted as a sequence of zero-sized NAL units. When playing the movie fragment, the HTTP streaming client parses the base media track and resolves the extractor NAL units. If an extractor NAL unit refers to a zero-sized NAL unit (i.e., enhancement NAL unit that was not received), it is ignored. Otherwise, an extractor NAL unit is resolved conventionally by placing the referred enhancement media data into the access unit. The example figure below presents a movie fragment in the form it is written to the MP4 file being composed. In the example, the DASH client has determined not to receive the enhancement layer data and hence the mdat box is zero-padded in the movie fragment written to the file. 
>  

I think deprecating the padding_flag would probably be ok, since:

1) In HEVC, such extractor-based construction of multi-layer bitstreams became less important, since it also support implicit reconstruction from multiple tracks. The draft VVC file format only support implicit reconstruction.

2) 10 years has passed since the proposal and almost 10 years since it appeared in the specification, and this feature is probably not used by any implementation.

3) As David points out, it is questionable whether readers would handle NAL units whose size is indicated to be 0 correctly like intended in the semantics of the padding_flag.

**Comment by dwsinger** [comment]
already deprecated in the 7th edition. Closing.
