### ISSUE TITLE
ISOBMFF Clarification to semantics of data_reference_index in SampleEntry

### ISSUE THREAD

**Issue by lkondrad** [MPEGGroup/FileFormat#15]
Section 8.5.2.3 of 14496-12 (14496-12-6th-ed-FDIS)

Currently data_reference_index of Sample Entry has the following semantic:

>data_reference_index is an integer that contains the index of the data reference to use to retrieve data associated with samples that use this sample description. Data references are stored in DataReferenceBoxes. The index ranges from 1 to the number of data references.

According to Section 8.7.2 there is exactly one DataReferenceBox in DataInformationBox. DataReferenceBox contains number of DataEntryBoxes and indexies of those DataEntryBoxes are signaled by data_reference_index in Sample Entry. 

consider making it more clear in the semantics of data_reference_index, e.g. 

>data_reference_index is an integer that contains the index of the ~~data reference~~ __DataEntryBox__ to use to retrieve data associated with samples that use this sample description. ~~Data references~~ __DataEntryBoxes__ are stored in DataReferenceBox~~es~~. The index ranges from 1 to the number of ~~data references~~ __DataEntryBoxes__.

Lukasz

**Comment by dwsinger** [comment]
addressed in the 7th edition
