### ISSUE TITLE
ISOBMFF Clarification on DataReferenceBox

### ISSUE THREAD

**Issue by lkondrad** [MPEGGroup/FileFormat#16]
Section 8.7.2 of 14496-12 (14496-12-6th-ed-FDIS)

DataEntryBoxes of type 'url' and 'urn' are stored in DataReferenceBox and not in the Data InformationBox. Please consider correcting as below: 

>Box Types: 'url ', 'urn '
>Container: ~~DataInformationBox~~ __DataReferenceBox__
>Mandatory: Yes (at least one of 'url ' or 'urn ' shall be present)
>Quantity: One or more

Additionally, two more DataEntryBoxes are defined in the Section, 'imdt' and 'snim'. However the Section contains the following paragraph with __shall__ statement. 

>"The entry_count in the DataReferenceBox shall be 1 or greater; each DataEntryBox within the DataReferenceBox __shall__ be either a DataEntryUrnBox or a DataEntryUrlBox."

Please consider removing the above paragraph or adapt it to allow for the usage of the other two defined DataEntryBoxes. 

Lukasz

**Comment by dwsinger** [comment]
also the DataReferenceBox contains an array of an undefined Type, 	

>	DataEntryBox(entry_version, entry_flags)	data_entry;

That type needs defining as a FullBox, and the four boxes that can be there should be derived from it.

sigh

**Comment by dwsinger** [comment]
editorially addressed in the revised 6th edition
