### ISSUE TITLE
bit-rate box not really suitable for live content

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/FileFormat#18]
The ISO file format states:

class BitRateBox extends Box(‘btrt’){
unsigned int(32) bufferSizeDB;
unsigned int(32) maxBitrate;
unsigned int(32) avgBitrate;
}

bufferSizeDB	gives	the	size	of	the	decoding	buffer	for	the	elementary	stream	in	bytes.	
maxBitrate	gives	the	maximum	rate	in	bits/second	over	any	window	of	one	second.	
avgBitrate	gives	the	average	rate	in	bits/second	over	the	entire	presentation.	

This is not really suitable for live content, where:
a) it is not feasible to compute maxBitRate over any windows as both future and past fragments might be unknown
b) avgBitrate need to be updated while the live stream is running, but when 
streaming it is not good to update the CMAF Header / Intialization segment each time
(also holds for 1)

A more live friendly defintion could be to add: 
*maxBitRate* -> in case unknown or changing over time, it may be set to the maximum expected average bit-rate over a 1 second window based on the containing encoding configuration
*avgBitRate* -> in case unknown or changing over time, it may be set to the target bit-rate based on the encoding configuration 

This would make usage more friendly in DASH and CMAF.

**Comment by cconcolato** [comment]
The current definition of `btrt` gives a promise about the average/max bitrate. Changing the semantics as you propose is non-backward compatible change I think. What would happen to a decoder that trusted the `btrt` value with old semantics but receives a stream that obeys the new semantics?
Usually bitrate information in http live streams is provided in the manifest. Can you describe the use of the `btrt` box in this case?

**Comment by dwsinger** [comment]
I think it's compatible for the live case to insert a promise into at least the maxBitRate — a not-to-exceed value. And similarly, you would insert into the abgBitRate the target long-term average you told your encoder to adhere to.

So, if you configured your stream to be a suitable for someone with a 200kb/s connection, you promise an average bit-rate of 200kb/s, and tell people what the max might be in max.

what am I missing?

**Comment by cconcolato** [comment]
@RufaelDev's definition for `maxBitRate` says 'expected' (meaning it is allowed to exceed that value), whereas in the current semantics one would interpret it as a strict value. If you cannot trust the value, that's a problem.

Regarding `avgBitrate`, this is probably less of a problem but the current semantics talks about the entire presentation. If you record a live stream that uses the new semantics to set the box values and try to validate the recorded file with old semantics (over the entire presentation), it might be invalid.

Until now, the semantics give a statement of fact about a file, not a promise about a stream.

**Comment by dwsinger** [comment]
@Rufael -- could the max not be the "I really won't exceed this" (though I may never reach it, either)?

Seems like the avgBitrate being a "long term configured average" or target bitrate is fine. If I say 200kb/s here, and then measure the stream for a few milli-eons and it's at 180 long-term, how do I know whether the bit-rate is going to rise for the next few milli-eons or not, to make it true?  (Though honestly, what use is a long-term average, anyway?)

**Comment by cconcolato** [comment]
> @rufael -- could the max not be the "I really won't exceed this" (though I may never reach it, either)?

wrong @RufaelDev 

> Seems like the avgBitrate being a "long term configured average" or target bitrate is fine. If I say 200kb/s here, and then measure the stream for a few milli-eons and it's at 180 long-term, how do I know whether the bit-rate is going to rise for the next few milli-eons or not, to make it true? (Though honestly, what use is a long-term average, anyway?)

I agree that's the right way to do it for live, but it's not the way it is defined today for on-demand. Should we have a new version of the box (e.g. v1) for live semantics?

**Comment by dwsinger** [comment]
So, formally, `avgBitRate` is defined  today such that
`sum(`over all tracks, `avgBitrate * trackDuration) ≅ filesize`. 
This also tells you something about de-multiplexing, how big de-multiplexed files might be. And I suppose it helps estimate segment sizes, though as segment duration drops the estimates become less and less accurate.
What else? What fails with 'live semantics' as suggested?

**Comment by dwsinger** [comment]
I seem to recall that the semantics of this box were inherited from MPEG-4 systems. Do we need to stay compatible with that (unused) system?

**Comment by jshouchin** [comment]
What harm would occur in an on-demand system if the value were set according to the live semantics (estimated average bit rate) but where the actual average bit rate never actually reached the specified average?

Are any systems still making "long-term" decisions on what quality to transmit based on a long-term average?

Dave noted that trying to use this to estimate file size is already imprecise. I see no harm in allowing this value to in effect being less precise. Yes, it could cause some system to transmit lower quality data than could have been carried over the stream. But likely that means you send 720p instead of 1080p momentarily. Are customers actually going to care or even notice?

**Comment by dwsinger** [comment]
So, I have no problem with the max truly being a max that the content actually adheres to, or is ensured will adhere to. So remove 'expected'.

`maxBitrate` gives the maximum rate in bits/second over any window of one second; this is a measured value for stored content, or a value that a stream is configured not to exceed;
`avgBitrate` gives the average rate in bits/second of the stream; this is a measured value (cumulative over the entire presentation) for stored content, or the configured target average bit-rate for a stream.

**Comment by RufaelDev** [comment]
thank you for considering this, i am ok aswell with this proposal

**Comment by dwsinger** [comment]
problematic if we store a live stream; maybe it's always a choice – measured, or a configured upper bound?

**Comment by dwsinger** [comment]
closing, fixed in the 7th edition
