### ISSUE TITLE
ISOBMFF What is mandatory in a file?

### ISSUE THREAD

**Issue by dwsinger** [MPEGGroup/FileFormat#2]
The ISO brands in the annex talk about reader requirements (what must be supported) and the MovieBox is marked as mandatory in the informative overview table, and described as mandatory in its section. Is there any doubt that a file that claims conformance to these brands must have a MovieBox, or should it be explicitly stated? The question comes up for e.g. HEIF files; do they conform to these brands or not?

**Comment by kgruen** [comment]
Legacy readers might "expect" the mandatory moov box. Should they be able to play HEIF files? 
Does it make sense to explicitly state for at least one of the more "contemporary" iso brands that the MovieBox may be missing?

**Comment by kashyapks** [comment]
MovieBox is mandatory in an ISOBMFF file, i.e. any file with ‘isom’ brand or any brand derived from it. The definition of MovieBox clearly specifies it as mandatory.

However, for HEIF files with image items only may not contain moov boxes. ‘mif1’ structural brand (for image items only) does not require the presence of any ISOBMFF brand and hence does not require the presence of MovieBox either. This is explicitly stated in the definition of ‘mif1’: “Note particularly that the brand 'mif1' does not mandate a MovieBox ('moov').”

No action is needed in our opinion.

**Comment by dwsinger** [comment]
so, the isom brands are not permissible on HEIF files that lack a MovieBox, OK. Use a mif1 or the like brand?

**Comment by dwsinger** [comment]
we note that there is a comment already in HEIF that Annex E brands are not mandated. Closing no action.
