### ISSUE TITLE
handler_type in stsd and sgpd syntaxes

### ISSUE THREAD

**Issue by jeanlf** [MPEGGroup/FileFormat#21]
Both stsd and sgpd use `unsigned int(32) handler_type` in their syntax, without  the handler type being documented.

The sample group description section (8.9.3.1) does not say anything about it,  while the sample description (8.5.2.1) states:
> Which type of sample entry form is used is determined by the media handler, using a suitable form, such as one defined in clause 12, or defined in a derived specification, or registration.

It would be cleaner to
- remove the `unsigned int(32) handler_type` in the syntax
- states in both section: "The syntax of the sample entry [sample groupd description entry] used is determined by both the format [grouping_type] four character code and the media handler type."

**Comment by dwsinger** [comment]
handled in the 7th edition
