### ISSUE TITLE
HEIF mirroring interpretation

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormat#22]
The spec says:
"axis specifies a vertical (axis = 0) or horizontal (axis = 1) axis for the mirroring operation."

One interpretation is that:
when axis = 0, the axis for the mirroring is vertical and therefore the left of the image becomes the right and the right becomes the left.
Similarly, when axis is 1, the axis is horizontal and the bottom becomes the top and vice versa.

Another interpretation is that a vertical mirroring (0) is when the image is modified vertically, i.e. when the bottom becomes the top and vice versa.

How do people implement it?

**Comment by dwsinger** [comment]
I think I need to apologize here; I was thinking the first when I wrote the text; but I should have been aware that EXIF uses the terms horizontal and vertical mirroring, which use the words horizontal and vertical in the second sense, which was going to, and has, caused confusion. I'm sorry.

**Comment by joedrago** [comment]
@ledyba-z I suspect this potential misunderstanding impacts your test images that use the `imir` transformation. I updated some of my documentation/syntax/headers to make libavif/avifenc much clearer too, as well as correcting my implementation in Vantage.

**Comment by dwsinger** [comment]
being addressed in amendment.2, closing
