### ISSUE TITLE
ISOBMFF Restricted sample entry transformation

### ISSUE THREAD

**Issue by lkondrad** [MPEGGroup/FileFormat#25]
based on 6th edition 14496-12, clause 8.15.2

> A restricted sample entry is defined as a sample entry on which the following transformation procedure has been applied:
> 1)	The four character code of the sample entry is replaced by a new sample entry code 'resv' meaning restricted video.
> 2)	A RestrictedSchemeInfoBox is added to the sample description, leaving all other boxes unmodified.
> 3)	The original sample entry type is stored within an OriginalFormatBox contained in the RestrictedSchemeInfoBox.

the second bullet says that RestrictedSchemeInfoBox is added to the sample description, which I was initially interpreting as SampleDescriptionBox. However, clause 8.15.3.1 says that RestrictedSchemeInfoBox is stored in Restricted Sample Entry or Sample Entry which I believe is the correct behaviour.

For clarity, I would proposed to correct the second bullet point to 

> 2)	A RestrictedSchemeInfoBox is added to the ~~sample description~~ sample entry, leaving all other boxes unmodified.

**Comment by podborski** [comment]
Note that the same probably applies to clause 8.17.2:

> 2)	A CompleteTrackInfoBox is added to the sample description, leaving all other boxes unmodified.

**Comment by cconcolato** [comment]
In the 7th edition, there are:
- 200 occurrences of "sample entry" (singular and plural)
- 70 "sample description" (singular and plural)

I would recommend:
- adding a note to the definition of "sample description" to say that it is equivalent to "sample entry"
- replace the 4 occurrences of "sample description entry" with "sample description"

**Comment by jeanlf** [comment]
shouldn't we pick one and stick with it rather than using two different terms for the same thing ?
We could of course keep the two terms defined and say that derive specifications might use one or the other, but termX is preferred.

**Comment by dwsinger** [comment]
see the WD of amendment (which does a large amount of cleaning up):

> A restricted sample entry is defined as a sample entry on which the following transformation procedure has been applied:
> 1)	The four character code of the sample entry is replaced by a new sample entry code as defined in table X below.
> 2)	A RestrictedSchemeInfoBox is added to the sampleentry, leaving all other boxes unmodified.
> 3)	The original sample entry type is stored within an OriginalFormatBox contained in the RestrictedSchemeInfoBox.
> 


yes, there is a space missing. sigh

**Comment by cconcolato** [comment]
@dwsinger I think the WD of Amendment should have a note saying that previous editions used the term "sample description" to mean "sample entry". Both have been used interchangeably for many years, it would be good to not invalidate all documents that use "sample description".

**Comment by dwsinger** [comment]
Add a note saying that sample description has also been used as a name for a sample entry.
