### ISSUE TITLE
[HEIF] Clarification on ispe semantics

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormat#26]
HEIF (N18310) says in 6.5.3.3:
> image_width specifies the width of the reconstructed image in pixels, as specified in 6.5.3.1.
> image_height specifies the height of the reconstructed image in pixels, as specified in 6.5.3.1.

First, the cross-reference to 6.5.3.1 does not make sense. It should be 6.3.

"reconstructed image" is defined as:
> "image (3.1.15) that results when the coded image item (3.1.5) is decoded or when the operation
(3.1.32) of the derived image item (3.1.8), if any, is applied"

6.3 says:
> - if the image item contains a coded image, the coded image is decoded and the reconstructed image is the output of the decoding process;
> - otherwise (the image item is a derived image item), the operation of the derived image item is applied to the input images of the derived image item to form the reconstructed image."

While the size of derived images is clear: for grid and overlay, the fields are coded; and for transforms, it is obtained from the input image (swap width/height in some rotations, ...), it is not so clear for coded images. In my view, we should have the same definition as for VisualSampleEntry width and height, which says:

> width and height are the maximum visual width and height of the stream described by this sample description, in pixels

The important part is "width and height of the stream" and it is up to the codec to define what they mean.

We should fix the reference in HEIF and maybe clarify the meaning of ispe width and height to say that this is as defined by the codec (especially in layered cases, depending with lsel and maybe other boxes).

**Comment by dwsinger** [comment]
addressed
