### ISSUE TITLE
'infe' flags

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormat#27]
It seems that there was a regression in the ISOBMFF specification.
N17277 (output from the Macao meeting) indicates:
```
aligned(8) class ItemInfoEntry
		extends FullBox('infe', version, flags) {
```
and also contains the text:
> The flags field of ItemInfoEntry with version greater than or equal to 2 is specified as follows:
> — (flags & 1) equal to 1 indicates that the item is not intended to be a part of the presentation.
> — (flags & 1) equal to 0 indicates that the item is intended to be a part of the presentation.

but the latest version N19301 (output from Alpbach) wrongly says:
```
aligned(8) class ItemInfoEntry
		extends FullBox('infe', version, 0) {
```

**Comment by dwsinger** [comment]
corrected in the 7th edition
