### ISSUE TITLE
14496-15 Sample format definition wrongly refers to one byte NAL header in Section 4.2.3.3 

### ISSUE THREAD

**Issue by fmaze** [MPEGGroup/FileFormat#33]
The generic definition of sample format currently defines a NALUnit as including one byte NAL header,
but depending on the specification, the NAL header may be coded on one or more bytes.

> NALUnit contains a single NAL unit. The syntax of a NAL unit is defined in the appropriate specification (e.g. ISO/IEC 14496-10) and includes both **the one byte** NAL header and the variable length encapsulated byte stream payload.

Above text could be rephrased as follows:

> NALUnit contains a single NAL unit. The syntax of a NAL unit is defined in the appropriate specification (e.g. ISO/IEC 14496-10 **for AVC or ISO/IEC 23008-2 for HEVC**) and includes both the **~~one byte~~** NAL **unit** header and the variable length **~~encapsulated byte stream~~NAL unit** payload.

**Comment by cconcolato** [comment]
Ye-Kui to check if the issue can be closed.

**Comment by yekuiwang** [comment]
OK, I will check.

**Comment by yekuiwang** [comment]
Fixed, for both the sentence in subclause 4.2.3.3 and the sentence in subclause 5.4.3.2.3, in WG03N0801_22325_14496_15_Ed6_draft_DAM2_text (Draft text of ISO/IEC 14496-15 6th edition DAM 2 Picture-in-picture support and other extensions).

**Comment by yekuiwang** [comment]
Hmm, tried, but failed to find how to close the ticket...

**Comment by fmaze** [comment]
I'm closing this ticket now
