### ISSUE TITLE
Forbid invalid `property_index` in `ItemPropertyAssociationBox` (`ipma`)

### ISSUE THREAD

**Issue by baumanj** [MPEGGroup/FileFormat#34]
See https://github.com/gpac/ComplianceWarden/issues/27

I feel like this is implied by the text of § 8.11.14, but it would improve clarity to make it explicit via the addition of some text like @rbouqueau suggested:

> The property index shall not exceed the number of property boxes in the ItemPropertyContainerBox contained in the same ItemPropertiesBox

**Comment by dwsinger** [comment]
add that the property_index shall not exceed the number of properties in the container

**Comment by cconcolato** [comment]
Implemented in the 8th edition https://dms.mpeg.expert/doc_end_user/documents/140_Mainz/wg11/MDS21996_WG03_N00717.zip
