### ISSUE TITLE
Question on item extent_length 0 

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormat#37]
An item extent_length field is allowed to be set to 0 with the following meaning:
>extent_length provides the absolute length in bytes of this metadata item extent. If length_size is 0, extent_length takes the value 0. If the value is 0, then length of the extent is the length of the entire referenced container.

I assume that the 'reference container' depends on the construction method. So my understanding is the following:
* if `construction_method` == 0, the `data_reference_index` indicates the reference container. 
  * if `data_reference_index` == 0 ("The data_reference_index may take the value 0, indicating a reference into the same file as this metadata"), then the "the length of the extent is the length of the entire" *file*. This does not make much sense though. You'd want the extent end to be the end of the file, but the extent length should be the file size minus the start offset.
  * if  `data_reference_index` != 0, the 'reference container' is either:
     * an external file, in which case it makes sense that the extent_length be the entire length of the referenced file.
     * an 'imdt' box, in which case, the 'referenced container' is the box and so the extent_length would be the box length, which does not make sense either. It should be the length of the box payload.
* if `construction_method` == 1, the 'referenced container' is the `idat` box, so again, the semantics are not clear. The length of the extent should be the length of the payload not of the container.
* if `construction_method` == 2, the 'reference container` is an item, and then it makes sense that the extent length if is the length of the entire item.

Comments?

**Comment by jeanlf** [comment]
> if data_reference_index == 0 ("The data_reference_index may take the value 0, indicating a reference into the same file as this metadata"), then the "the length of the extent is the length of the entire" file. This does not make much sense though. You'd want the extent end to be the end of the file, but the extent length should be the file size minus the start offset.

No, I think this is on purpose, in order to say "this item is the container file itself"

> an 'imdt' box, in which case, the 'referenced container' is the box and so the extent_length would be the box length, which does not make sense either. It should be the length of the box payload.

I agree that the 'reference container' is not defined for imdt for items, we should clarify that it is the box payload (in dinf, we only talk about offsets).

> if construction_method == 1, the 'referenced container' is the idat box, so again, the semantics are not clear. The length of the extent should be the length of the payload not of the container.

same thing indeed.

Should we add something along:
"When the reference container is an IdentifiedMediaDataBox as indicated by the `data_reference_index`, the reference bytes are the payload of the IdentifiedMediaDataBox (exluding the box header).
When the reference container is an ItemDataBox as indicated by the `construction_method == 1`, the reference bytes are the payload of the ItemDataBox (exluding the box header).
"

BTW, the semantics for iloc use `data-reference-index` instead of `data_reference_index`

**Comment by dwsinger** [comment]
we should say it's the content length, and residual length. perhaps also a note to say it's typically only used for whole (external?) files? draft text that is explicit by construction_method and takes offsets (and box headers) into account

**Comment by cconcolato** [comment]
While working on this, a new question came up. 

The current text says:
> The `data_reference_index` may take the value 0, indicating a reference into the same file as this MetaBox, or an index into the data references in the DataInformationBox in the containing MetaBox, with value 1 indicating the first entry in the data reference list.

This gives the impression that the only way to have a 'same file' reference is to set `data_reference_index` to 0. Isn't it possible to set it to 1, have the first `dref` entry be an `urn` with the flag 0x000001 set? That would also mean 'same file', no?

**Comment by dwsinger** [comment]
I think we wanted a simpler way to indicate "same file" but you're right, we didn't forbid the more complex one as far as I know

**Comment by cconcolato** [comment]
I propose to update 8.11.3.1 by replacing the entire text from
> The `construction_method` fields indicates ...

with

> The `construction_method` field indicates the ‘construction method’ for the item:
> i. file_offset: by absolute byte offsets into the file or the payload of `IdentifiedMediaDataBox` referenced by `data_reference_index`; (`construction_method` == 0)
> ii. idat_offset: by byte offsets into the `ItemDataBox` in the same `MetaBox`; neither the `data_reference_index` nor `item_reference_index` fields are used; (`construction_method` == 1)
> iii. item_offset: by byte offset into the items indicated by the `item_reference_index` field, which is only used (currently) by this construction method. (`construction_method` == 2).
>
> The `item_reference_index` is only used for the method item_offset; it indicates the 1-based index of the item reference with referenceType `'iloc'` linked from this item. If `index_size` is 0, then the value 1 is implied; the value 0 is reserved.
>
> The `data_reference_index` may take the value 0, indicating a reference into the same file as this `MetaBox`, or an index into the data references in the `DataInformationBox` in the containing `MetaBox`, with value 1 indicating the first entry in the data reference list.
> NOTE 1 A reference to the ‘same file’ can also be coded by setting `data_reference_index` to a non-zero value pointing to a data reference entry of type `‘urn ’` with the flag `0x000001` set. However, using `data_reference_index` 0 is recommended.
>
> Items may be stored fragmented into extents, e.g. to enable interleaving. An extent is a contiguous subset of the bytes of the resource identified by an offset and a length; the resource is formed by concatenating the extents in the order specified in this box. The size of the item is the sum of the extent lengths.
> NOTE 2 Extents can be interleaved with the chunks defined by the sample tables of tracks.
>
>The offsets are relative to a data origin. That origin is determined as follows:
>1. when `construction_method` = 0 (file offset)
>   a. when the data reference points to the ‘same file’
>     - when the MetaBox is in a Movie Fragment, the data origin is the first byte of the enclosing MovieFragmentBox (as for the `default-base-is-moof` flag in the `TrackFragmentHeaderBox`);
>
>    b. when the data reference indicates a `DataEntryImdaBox` or `DataEntrySeqNumImdaBox`, the data origin is the first byte of the payload of the corresponding `IdentifiedMediaDataBox`;
>
>    c. in all other cases, the data origin is the beginning of the file identified by the data reference;
>
>2. when `construction_method` = 1 (idat offset), the data origin is the beginning of `data[]` in the `ItemDataBox`;
>
>3. when `construction_method` = 2 (item offset), the data origin is the first byte of the concatenated data (of all the extents) of that item;
> NOTE 3 There are offset calculations in other parts of this file format based on the beginning of a box header; in contrast, item data offsets are calculated relative to the box payload.
>
> A value of 0 for extent_length is interpreted as follows:
> 1. when `construction_method` = 0 (file offset)
>   a. when the data reference points to the ‘same file’, the length of the extent is assumed to be the length of the data between the origin (as determined above) and the end of the file.
>    b. when the data reference indicates a `DataEntryImdaBox` or `DataEntrySeqNumImdaBox`, the `extent_length` is assumed to be the length of the payload of the corresponding `IdentifiedMediaDataBox`.
>
>    c. in all other cases, the `extent_length` is assumed to be the entire length of the referenced file.
> 2. When `construction_method` == 1 (idat offset), the length of the extent is assumed to be the length of the payload of the `idat` box.
> 3. if `construction_method` == 2 (item offset), the length of the extent is assumed to be the size of the item.
>
> If only one extent is used (`extent_count` = 1) then either or both of the offset and length may be implied, i.e. by setting `offset_size` or `length_size` to 0.
>
> References into the same file, or items divided into more than one extent, should have an explicit offset and length, or use a MIME type requiring a different interpretation of the file, to avoid infinite recursion.
>
> Some referenced data may itself use offset/length techniques to address resources within it (e.g. an MP4 file might be ‘included’ in this way). Normally such offsets in the item itself are relative to the beginning of the containing file. The field ‘base offset’ provides an additional offset for offset calculations within that contained data. For example, if an MP4 file is included within a file formatted to this document, then normally data-offsets within that MP4 section are relative to the beginning of file; the base offset adds to those offsets.

(The last 2 paragraphs exists already in the existing text and I think I understand their meaning but they are hard to understand and could use either a rephrasing or examples.)

In 8.11.3.3, replace:
> `extent_length` provides the absolute length in bytes of this metadata item extent. If `length_size` is 0, `extent_length` takes the value 0. If the value is 0, then length of the extent is the length of the entire referenced container.

with

> `extent_length` provides the absolute length in bytes of this metadata item extent. If `length_size` is 0, `extent_length` takes the value 0.

**Comment by dwsinger** [comment]
I think that the implied extent_length should be the _residual_ length of the container (after any explicit offset, no)?

**Comment by cconcolato** [comment]
Right. I missed that. I updated the text.

**Comment by cconcolato** [comment]
Implemented in https://dms.mpeg.expert/doc_end_user/documents/140_Mainz/wg11/MDS21996_WG03_N00717.zip
