### ISSUE TITLE
[HEIF] Add additional restriction to colr box from HEIF DAmd2

### ISSUE THREAD

**Issue by baumanj** [MPEGGroup/FileFormat#39]
See https://github.com/AOMediaCodec/av1-avif/issues/164

My suggestion would be to change the `colr` box quantity to:
> Quantity (per item): 0, 1 (unrestricted) or 2 (with restrictions):
> - One for a `colour_type` value of 'nclx', 'rICC' or 'prof'
> - One for a `colour_type` value of 'rICC' or 'prof' and one for a `colour_type` value of 'nclx'
with `colour_primaries = 2` and `transfer_characteristics = 2` (2 indicating "unspecified", since these data are supplied by the ICC profile instead)

**Comment by leo-barnes** [comment]
@podborski 
This is the issue!

**Comment by podborski** [comment]
@leo-barnes during MPEG 137 this was raised and it should be addressed in the WD of amendment:

>Into the WD of amendment. We also pick up the corrections on essential bit and clarifying the JPEG configuration property (issue [61](http://mpegx.int-evry.fr/software/MPEG/Systems/FileFormat/HEIF/-/issues/61)), which needs to make clear that we have a property and a box with the same shape, and the Github issue #39 on the color property.

**Comment by cconcolato** [comment]
Implemented into "Text of ISO/IEC 23008-12 DAM 1 Support for progressive rendering, signaling, and other improvements"
