### ISSUE TITLE
[ISOBMFF]: `CleanApertureBox` (`clap`) offsets should be signed

### ISSUE THREAD

**Issue by baumanj** [MPEGGroup/FileFormat#41]
See ISO/IEC 14496-12:2020 § 12.1.4 Pixel aspect ratio and clean aperture

> For `horizOff` and `vertOff`, D shall be strictly positive and N may be positive or negative.

However, `horizOffN` and `vertOffN` are defined as `unsigned int(32)`. Should they more correctly be `int(32)`?

**Comment by cconcolato** [comment]
We have implemented the change in https://dms.mpeg.expert/doc_end_user/documents/140_Mainz/wg11/MDS21996_WG03_N00717.zip but need to implement the same for the corresponding sample group
