### ISSUE TITLE
Definition of syntax interpretation 

### ISSUE THREAD

**Issue by lkondrad** [MPEGGroup/FileFormat#42]
ISO/IEC 14496-12:4.2 clearly specifies how to interpret the syntax sub-clauses.

> The definitions of boxes are given in the syntax description language (SDL) defined in ISO/IEC 14496-1. 

In ISO/IEC 14496-15, and probably other derived specifications, there is nothing mention about how to interpret syntax sub-clauses. We just assumed that is the same as for the base specification. 

I think it would be good to provide such information explicitly.

**Comment by dwsinger** [comment]
we probably ought to say that we use the SDL as defined in 14496-1, with the additions in 14496-12, and random errors introduced by the editors; in all specs based on 14496-12.

**Comment by dwsinger** [comment]
let's work out what the extensions are and improve 4.2.1 by at least documenting them

**Comment by cconcolato** [comment]
Some elements of this issue are addressed in the 8th edition, with some NB comments on the `=` operator. We should probably close this issue and add a mandate to make all File Format specs SDL-compatible.
