### ISSUE TITLE
[ISOBMFF]  Change data-reference-index to data_reference_index

### ISSUE THREAD

**Issue by lkondrad** [MPEGGroup/FileFormat#43]
Based on the WG03N0233 (Text of ISO/IEC FDIS 14496-12 7th edition ISO Base Media File Format) version of the document 

In 8.11.3.2 Syntax we have `data_reference_index` while in 8.11.3.3 Semantics we have `data-reference-index `

**Comment by dwsinger** [comment]
to fix in the upcoming amendment

**Comment by dwsinger** [comment]
make sure iloca nd stsd are consistent and the semantics match the syntax

**Comment by cconcolato** [comment]
Implemented https://dms.mpeg.expert/doc_end_user/documents/140_Mainz/wg11/MDS21996_WG03_N00717.zip
