### ISSUE TITLE
Default FullBox values for `EntityToGroupBox`

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#44]
I would like to understand how the default values for `version` and `flags` are handled.

In many cases the default syntax of `EntityToGroupBox` is used when defining a new entity group. 
For example `'altr'` from ISOBMFF or `'ster'` from HEIF are not extending the `EntityToGroupBox`.
However, neither specification says what the default values for `FullBox.version` and `FullBox.flags` should be if the default syntax of `EntityToGroupBox` is used. Shouldn't we mandate those to be set to zero just to make it more future-proof and avoid potential issues if one day someone decides to extend the default definition?

Maybe putting a note to 8.18.3 would be sufficient. Something like:

> NOTE: If for a specific `grouping_type` value the default syntax of `EntityToGroupBox` is used, both `version` and `flags` should be set to `0`

**Comment by fmaze** [comment]
Hi Dimitri,

This is an interesting question. I have a slightly different understanding than yours.  

IIUC, `FullBox.version` and `FullBox.flags` should not be interpreted  relatively to the default syntax of the `EntityToGroupBox`, but relatively to the `grouping_type` of the `EntityToGroupBox`.  
For instance, you could imagine in future a new version of `'ster'`  introducing new syntax elements dedicated to 'ster' and based on the same default syntax of `EntityToGroupBox`.

Therefore, if my understanding is correct, we could add something more like:
> By default, both `version` and `flags` should be set to 0 if not defined otherwise for a `grouping_type`

**Comment by podborski** [comment]
Yeah, I actually mean the same thing. `grouping_type` is a type of the `FullBox` there is just no specific syntax element defined in some cases and it's not clear what `version` and  `flags` should be. Your sentence is clearer.

**Comment by cconcolato** [comment]
> By default, both `version` and `flags` should be set to 0 if not defined otherwise for a `grouping_type`

"should" is too soft. It should be "shall".

**Comment by dwsinger** [comment]
in 8.18.3.3 say that version and flags shall be 0 unless defined for the grouping_type

**Comment by podborski** [comment]
Implemented in 8th edition as:

> version and flags shall be 0 unless defined otherwise for the grouping_type.
