### ISSUE TITLE
Question on `adda` and `adrc`

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#45]
I'm transferring this issue from https://github.com/mp4ra/mp4ra.github.io/issues/136 as it seems to be more related to this group than to registration authority. 

I had a question on definitions for `adda` and `adrc` track references. It's not really clear, where those track references are actually defined. mp4ra points to 23003-4 but I could not find them there. I checked the AMD1 of 23003-4 and could find a table (see below) mentioning that  `adda` and `adrc` are defined in Part 12 but this seems not to be true as there are no definitions for those in clauses 6.x.x.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40"><div align="center" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

File Format payload | FourCC | Version | Defined in ISO/IEC | Defined in sub-clause | Loudness Control profile | Dynamic Range Control profile
-- | -- | -- | -- | -- | -- | --
Track reference for additional audio track | adda | n/a | 14496-12 | 6.4.5 | a | a
Track reference for DRC metadata track | adrc | n/a | 14496-12 | 6.1.1 |   | b

</div></html>

In Part 12 `adda` is mentioned in clause 12.2.6. I believe we should also add `adda` entry to section 8.3.3.3 to keep all track references defined in Part 12 in one place.

And what about `adrc`? Is it really defined in 23003-4, did I miss it somehow?

**Comment by dwsinger** [comment]
Indeed, adda is in part 12, but only in narrative text; and adrc somehow is not at all.

**Comment by dwsinger** [comment]
add to the draft amendment; maybe split the track reference types each into their own subsection (8.3.3.3)

**Comment by podborski** [comment]
Added to the defect report of ISOBMFF.

**Comment by cconcolato** [comment]
Indeed, this is the defect report. We should probably move that text into an amendment.

**Comment by podborski** [comment]
In the WD. Can be closed
