### ISSUE TITLE
'svop' vs 'svdr'

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#47]
SVCDependencyRangeBox is defined with 'svop' in the syntax but svdr is listed in definition. Which one is correct?

I assume we should keep `svdr` as this one is also registered at mp4ra. And change:

```cpp
class SVCDependencyRangeBox extends Box('svop') ...
```

to 

```cpp
class SVCDependencyRangeBox extends Box('svdr') ...
```

**Comment by yekuiwang** [comment]
I will handle this.

**Comment by podborski** [comment]
@yekuiwang is this one already addressed? I don't remember if we put it in the amendment or not.

**Comment by yekuiwang** [comment]
> @yekuiwang is this one already addressed? I don't remember if we put it in the amendment or not.

Oh I man I forgot this one. I just took a note in my to-do list to make sure to include this into the FDIS text to be output from this Oct. 2023 MPEG meeting.

**Comment by yekuiwang** [comment]
@podborski Aha, that was actually integrated into Amd.1! Just integrated into the FDIS text I am editing anyway.

**Comment by cconcolato** [comment]
@yekuiwang @podborski can one of you confirm and close this issue?

**Comment by yekuiwang** [comment]
Confirmed. Closing now.

**Comment by yekuiwang** [comment]
@cconcolato I could not figure out how to close this issue; probably I cannot. @podborski you should be able to.
