### ISSUE TITLE
RtpReceptionHintSampleEntry is undefined

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#49]
There is no definition of `RtpReceptionHintSampleEntry` is ISOBMFF but its used to define `ProtectedRtpReceptionHintSampleEntry` in 9.4.5.2:

```cpp
Class ProtectedRtpReceptionHintSampleEntry
	extends RtpReceptionHintSampleEntry ('prtp') {
	ProtectionSchemeInfoBox		SchemeInformation;
}
```

**Comment by mhannuksela** [comment]
9.4.1.2 specifies `ReceivedRtpHintSampleEntry`, which ought to be used to derive `'prtp'`.

**Comment by cconcolato** [comment]
This is covered in the defect report. Closing this issue.
