### ISSUE TITLE
W21173 – suggested slight re-structuring

### ISSUE THREAD

**Issue by dwsinger** [MPEGGroup/FileFormat#51]
Rather than saying that uncv is the only sample entry (raw video shall be carried using it), I think it might be safer to say that the document covers carriage of raw video, and defines the sample entry/ies that can be used. So, have a section on 'general uncompressed video' that defines uncv and its parameters and so on, but admit the possibility that something comes along that doesn't fit that, and we invent a second or third sample entry.

We should make some things general, though, and that includes what the file format fields mean, the profile indicator, and so on.

so, general section, applicable to all sample entries, and then for now one section on uncv?

**Comment by cconcolato** [comment]
Implemented in the current text
