### ISSUE TITLE
Raw video interlaced/field handling could be clearer

### ISSUE THREAD

**Issue by dwsinger** [MPEGGroup/FileFormat#52]
The descriptions in the old [Ice-Floe 19](https://developer.apple.com/library/archive/technotes/tn2162/_index.html) document might be helpful.

 in short the values mean:
- 	1 = top half of buffer contains upper field, lower half of buffer contains lower field
- 	6 = top half of buffer contains lower field, lower half of buffer contains upper field
- 	9 = buffer contains interleaved fields, top line of buffer belongs to temporally earlier field (colloquially known as “top field first”)
- 	14 = buffer contains interleaved fields, top line of buffer belongs to temporally later field (colloquially known as “bottom field first”)

also:

1. If field_ordering is 0 it is stated that there is only one field (picture). However, it is not clear which parity this picture has.
2. as hinted in (1) maybe we should be using the terminology of a picture (as in the video coding specs)
3. if we understand this correctly, the parameters are sequence level. If so, we see no support for dangling fields/field pictures. Quite often some systems may not be able to capture a particular field and only one of them exists in the video sequence (either top or bottom).
4. we are not very clear from the description if this is about an interlace frame picture (interleaved at the sample column level), or two complementary field pictures (interleaved at the picture level). The first is more common but the second is also quite common for some applications.
5. It is quite possible that the field order changes (possibly as a consequence of a dangling field) even in interlace frame picture representations.

**Comment by dwsinger** [comment]
do we need to use sample groups to define whether a sample has both fields, or only one (and which)?

**Comment by dwsinger** [comment]
what about SEIs like 3:2 pulldown?

**Comment by jeanlf** [comment]
DIS text has all this signaling except 3:2 pulldown (reserved bits are present if we later need that).
