### ISSUE TITLE
Minor editorial improvements/corrections to the WD of ISO IEC 23001-17

### ISSUE THREAD

**Issue by yekuiwang** [MPEGGroup/FileFormat#53]
I read through the WD text David sent to the mp4-sys reflector earlier today (Feb. 3, 2022), and made some minor editorial improvements/corrections when reading it.  Attached here for consideration:
[WD of ISO IEC 23001-17_yk0.docx](https://github.com/MPEGGroup/FileFormat/files/7999347/WD.of.ISO.IEC.23001-17_yk0.docx)

**Comment by jeanlf** [comment]
I think we can close this one now

**Comment by yekuiwang** [comment]
Sure. Let me close it.
