### ISSUE TITLE
Clarify how IPTC-IIM can be stored in HEIF

### ISSUE THREAD

**Issue by leo-barnes** [MPEGGroup/FileFormat#54]
There have been multiple people over the years who have wanted to transcode JPEGs with IPTC-IIM segments to HEIF. Currently the HEIF spec does not describe how IPTC-IIM should be stored. Most people have worked around this by converting IPTC-IIM to the newer IPTC-XMP format, which can then be written as a regular HEIF XMP payload.

But it has also led to some codebases coming up with their own ways of doing it:
https://github.com/strukturag/libheif/blob/a7425be338142c2261155824b64d7f1ed8c0705c/libheif/heif.h
(search for iptc)

After reading through various specs, I've come to the conclusion that HEIF *does* actually already support storing IPTC-IIM as is, but we should probably add a note to the spec to document this so that everyone can converge on the same interpretation.

The IPTC spec that describes IPTC-IIM is this one: https://www.iptc.org/std/IIM/3.0/specification/IIMV3.PDF

Given that HEIF supports URI item types, and given that IPTC has [registered a URN namespace](https://www.rfc-editor.org/rfc/rfc3937.html), it looks like using an item type of `uri ` and a URI of `urn:iptc:std:IIM:3.0:spec` would be a possible way of marking an IPTC-IIM payload as such without actually reserving any specific item type for it.

**Comment by leo-barnes** [comment]
My proposal would be to either document the `uri ` usage, or to reserve the `iptc` item type for IPTC-IIM and add that to the spec.

**Comment by farindk** [comment]
This might also be of interest:
https://web.archive.org/web/20120131102845/http://www.metadataworkinggroup.org/pdf/mwg_guidance.pdf

See especially Figure 6 on page 27 for XMP/IPTC interoperation.

**Comment by leo-barnes** [comment]
> This might also be of interest: https://web.archive.org/web/20120131102845/http://www.metadataworkinggroup.org/pdf/mwg_guidance.pdf
> 
> See especially Figure 6 on page 27 for XMP/IPTC interoperation.

Thanks. I *knew* I had seen some text that more or less marked IPTC-IIM as deprecated, but couldn't remember where.

**Comment by leo-barnes** [comment]
From the reply in 
https://github.com/strukturag/libheif/issues/124
it looks like the main use case for IPTC-IIM is for backup storage of the unmodified metadata. This seems like a valid use-case.

Maybe be could add official IPTC-IIM support in HEIF, but have a note that says conversion to IPTC-XMP is preferred unless it is for backup purposes or something like that.

**Comment by farindk** [comment]
Yes, @leo-barnes, that would also be my preferred approach. Especially since it is in line with the MWG guidance document.

I guess that it is still easily possible to change the 'iptc' ID. DigiKam only writes the data but leaves reading to the Exiv2 library. This library uses libheif to read it back, but the support for heif has not yet been merged into the Exiv2 master branch. It is here:
https://github.com/cgilles/exiv2/blob/3a12d489d34a0fee9b1619befa757a4b0975102d/src/heifimage.cpp#L258

I could add a function to the API that extracts the IPTC metadata, which looks for the new ID but still accepts files with the old one, just in case.

**Comment by leo-barnes** [comment]
MPEG 143:
Accepted into Amendment 2.
