### ISSUE TITLE
HEIF needs a reduced header mode

### ISSUE THREAD

**Issue by leo-barnes** [MPEGGroup/FileFormat#59]
For small files, the current structure of headers in HEIF is pretty bloated. It's more or less impossible to get the size of the headers themselves down to less than 300 bytes, which may be a significant portion of the file for smaller images.

It would be beneficial to have a reduced header mode that could be used for simple, small images like these.

Things it should not support:
- HEIF tiling/overlay
- Image collections/sequences
- Auxiliary images (except alpha)
- Groups

Things it should *probably* not support (if you need these, ~300 bytes of headers is probably not as much of a deal):
- Thumbnail
- Metadata
- ICC profiles

Things it should support:
- A single coded item with 1, 3 and potentially 4 channels (for any future codec that can support alpha)
- An optional second coded item for alpha
- NCLX color

Files would should still start with an `ftyp` box so they are identifiable as HEIF, but after that we would need to look into the minimal amount of boxes and overhead needed to support the things listed above.

**Comment by leo-barnes** [comment]
MPEG 143: Discussed during meeting, will be explored further in future meetings.

**Comment by cconcolato** [comment]
MPEG 145: We have an exploration on going, see https://www.mpeg.org/wp-content/uploads/mpeg_meetings/144_Hannover/w23216.zip

**Comment by cconcolato** [comment]
Given that we now have a [Working Draft](https://www.mpeg.org/wp-content/uploads/mpeg_meetings/146_Rennes/w23988.zip) for this technology, I'm closing this issue.
