### ISSUE TITLE
Track reference definitions should use shall statements about the underlying track types

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormat#63]
Track reference definitions should use shall statements about the underlying track types. For example, regarding `auxl`, the ISOBMFF spec says:
> 'auxl': this track contains auxiliary media for the indicated track (e.g. depth map or alpha plane for video).

"auxiliary media" is not defined but "auxiliary video" is:
> Auxiliary video media uses the 'auxv' handler type in the HandlerBox of the MediaBox, as defined
in 8.4.3.

I think the intent here is that `auxl` should be used only on tracks of type `auxv`. This should be clarified. Each track reference should list the track types to which it applies, if possible. 

This is related to https://github.com/gpac/ComplianceWarden/issues/38

**Comment by podborski** [comment]
In addition to that some clarification on auxiliary sequence tracks in section 7.1 in HEIF could also be helpful. 

> In order to distinguish image sequences from video, the handler type in the HandlerBox of the track is 'pict' to indicate an image sequence track. 

some pointer to clause 7.5 could be useful here.

**Comment by jeanlf** [comment]
I'm not sure I agree here. It is currently legal to have a video track (`vide` handler) used as an auxiliary track using `auxl` (same goes for `vdep` and `vplx`) for another track. There is no requirement that the auxiliary track is actually a video track: I could use a json/svg track describing alpha/depth and use `auxl`/`vdep`/`vplx`.

I think it should be a restriction from HEIF to only allow `auxl` on tracks with handler types `auxv`.

I however agree that we should clarify this in part 12, e.g.  add a note indicating that derived specifications may further restrict the media type of tracks holding track references.
