### ISSUE TITLE
audit of DIS 8th Ed for unregistered MIME fields

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/FileFormat#68]
1. fileindex parameter - there is an informative citation to 23001-14. This needs to be normative.
2. itemtypes parameter - not defined. It might be the same as the IANA registration parameter of the same name found here?  https://www.iana.org/assignments/media-types/image/heic
3. essential parameter (new in 8th Ed) - not defined.

**Comment by cconcolato** [comment]
We note that Annex K of ISOBMFF defines "Use of IETF RFC 6381 for ISOBMFF files" and is probably more precise than what's in RFC 6381. RFC 6381 should probably be updated to point to this text. We should probably ask IANA to refresh, the MIME type for `video/mp4` was last refreshed in 2011: https://www.iana.org/assignments/media-types/video/mp4.
