### ISSUE TITLE
Is `jpgC` required for an item of type `jpeg`?

### ISSUE THREAD

**Issue by leo-barnes** [MPEGGroup/FileFormat#72]
Note 1 in H.2.1 is slightly confusing:
> NOTE 1 The storage as image items of type 'jpeg' is preferred, as meta-data is separated, and JPEG header information may be shared. If image items of MIME type 'image/jpeg' are used, it is possible to have the same coded image content in an image item of type 'jpeg' present in the file, sharing the storage of both image and metadata by referring to the same data using appropriate item constructors in the item location box.

`as meta-data is separated` seems to indicate that if `jpeg` is used, metadata is _always_ separated using a `jpgC` box.

Our reading of the rest of the section on JPEG-in-HEIF is that `jpgC` is optional and _may_ be used to share Huffman tables and quantization tables between `jpeg` items, but it is not a requirement. (And that `jpgC` is only allowed for `jpeg` item types, not MIME item types with sub-type `image/jpeg`.)

If our understanding is correct, the note should maybe be changed to:
> NOTE 1 The storage as image items of type 'jpeg' is preferred, as meta-data **may be** separated

**Comment by farindk** [comment]
Similarly,
````
Quantity (per item): Zero or one for an image item of type 'jpeg'
````
might be clarified as follows:
````
Quantity (per item): Zero for an image item with MIME sub-type 'image/jpeg' or
                     at most one for an image item of type 'jpeg'
````
