### ISSUE TITLE
content_encoding for mski item

### ISSUE THREAD

**Issue by farindk** [MPEGGroup/FileFormat#75]
ISO/IEC 23008-12:2022 specifies an image item with `item_type=mski` for lossless storage of region masks.
Section 6.10.2.1 says that the `mski` data may be compressed as specified in the `infe` box's `content_encoding` of this item.

However, it is not possible to specify any `content_encoding` as this is only included in the `infe` box if `item_type=mime` (infe box version 2, 3). Box versions 0,1 have `content_encoding`, but no `item_type`.

Is this a defect in the standard or am I missing something?

**Comment by cconcolato** [comment]
Looks like a defect indeed. Thank you for the report. We'll more on a fix asap.
We should have been more careful and should have enforced requiring bitstreams before finalizing the standard.

**Comment by cconcolato** [comment]
Fixed in FDAM1 of 2nd Edition by removing the sentence saying "may be compressed".
