### ISSUE TITLE
OperatingPointRecord (oinf) syntax issue

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#78]
In ISO/IEC 14496-15:2022(E) Section 9.6.2.2 the syntax for `OperatingPointRecord` appears to have a typo.

Specifically, the operating points loop starts with:

```
for (i=0; i<num_operating_points) {
```

and probably should read:

```
for (i=0; i<num_operating_points; i++) {
```

(I don't see anything else that would otherwise increment the loop).

It looks OK in the `vopi` (VVC) variant.

**Comment by yekuiwang** [comment]
Good catch, thanks! Integrated into WG03 N0994 (Potential Improvements of ISO/IEC 14496-15 6th edition DAM 2 Picture-in-picture support and other extensions). This issue can now be closed.
