### ISSUE TITLE
Valid targets for `cdsc` reference type

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#82]
`cdsc` is used as the reference type for track reference and also for image items, plus things like regions.

Is it intended that `cdsc` should only be used where the target is a track or image-like item? 

That is, it is valid for an item to describe another item that is not an image item? For example, metadata describing another metadata item?

**Comment by leo-barnes** [comment]
I think it's perfectly valid to have metadata describing metadata from a purely syntactical view. But none of the metadata types in HEIF/ISOBMFF really make sense to "nest", so it will probably only make sense to use with custom metadata payloads, which are non-portable in any case.

**Comment by bradh** [comment]
I note that some of the files in https://github.com/MPEGGroup/FileFormatConformance/pull/108/files have nested `cdsc`.
 For example, the region-polygon.heic example has Item 2 -[cdsc]-> Item 100, and Item 100 -[cdsc]-> Item 1. Item 1 and 2 are `hvc1` and Item 100 is `rgan`.

**Comment by fmaze** [comment]
Thanks for this example, unfortunately, it seems this conformance vector is currently invalid.
In region-polygon.heic example, we should rather have **Item 100 -[eroi]-> Item 2**, and Item 100 -[cdsc]-> Item 1.  

In 23008-12 2nd ed. clause 6.10.3, (and future update in latest draft of 23008-12 2nd ed. FDAM1 clause 11.3.1), it is stated that region item is associated with:  
- _"metadata items, using an item reference of type 'cdsc' from the metadata item to the region item"_
- _"image items (...), using an item reference of type 'eroi' from the region item to the image item (...)"_

**Comment by podborski** [comment]
https://github.com/MPEGGroup/FileFormatConformance/pull/137

**Comment by cconcolato** [comment]
@bradh given that the files are now fixed, do you think the text needs update?

**Comment by bradh** [comment]
I'm OK with the updated wording.
