### ISSUE TITLE
ISO/IEC 14496-12:2022 Clause 8.11.12 (Item reference box) uses referenceType and reference_type inconsistently

### ISSUE THREAD

**Issue by wantehchang** [MPEGGroup/FileFormat#83]
ISO/IEC 14496-12:2022 Clause 8.11.12 (Item reference box) uses `referenceType` and `reference_type` inconsistently.

Clause 8.11.12.2 (Syntax) uses `referenceType`.

Clause 8.11.12.3 (Semantics) uses `reference_type`.

**Comment by mhannuksela** [comment]
Thanks for reporting the inconsistency. I aligned the semantics to the syntax in the 14496-12 8th Ed. revised 2nd DIS text that is being prepared.

**Comment by cconcolato** [comment]
Confirmed in the 8th edition.
