### ISSUE TITLE
ItemPropertyAssociationBox syntax re-uses loop variable

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#86]
In ISO/IEC 14496-12:2022(E) Section 8.11.14.2, the syntax for the ItemPropertyAssociationBox has two loops. The outer loop is over entries in the box, and the inner loop is over associations within the entry.

They both use `i` as the loop variable. 

It would be clearer if they used different variables (e.g. `j` for the association count).

(I feel like I may have reported this problem previously, although I couldn't find an issue for it, and that could have been a similar issue in some other box).

**Comment by mhannuksela** [comment]
Thank you for the bug report. This has been fixed as suggested in the 8th edition text of ISO/IEC 14496-12, which is currently at DIS stage.
