### ISSUE TITLE
On ItemReferenceBox version 1 in HEIF

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#87]
In HEIF we have this text in clause 6.6.1:

> The number of `SingleItemTypeReferenceBoxes` with the box type 'dimg' and with the same value of from_item_ID shall not be greater than 1.

`SingleItemTypeReferenceBoxes` is also mentioned in a bunch of derived image items.

However, in ISOBMFF the `ItemReferenceBox` is defined as:

```cpp
aligned(8) class ItemReferenceBox extends FullBox('iref', version, 0) {
	if (version==0) {
		SingleItemTypeReferenceBox				references[];
	} else if (version==1) {
		SingleItemTypeReferenceBoxLarge	references[];
	}
}
```

Allowing also item references to be specified using the `SingleItemTypeReferenceBoxLarge`. To me this seems to be a little bit ambiguous because I don't see a clear restriction of `ItemReferenceBox` to be version 0 only in the HEIF spec. I see that the `mif1` brand actually mentions the `iref` versions 0 and 1.

Table 3 — Boxes to be supported under the `mif1` brand
|Hierarchy of boxes | Version | Box description|
| --- | --- | --- |
| ... | ... | ... |
|`iref`|0, 1|item reference box|
| ... | ... | ... |

**Comment by leo-barnes** [comment]
This has been fixed in the 3ed amd2 draft. All mentions of `SingleItemTypeReferenceBox` were changed to `SingleItemTypeReferenceBox` or `SingleItemTypeReferenceBoxLarge`.
