### ISSUE TITLE
AuxiliaryTypeProperty syntax

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#88]
In HEIF we have this definition:

```cpp
aligned(8) class AuxiliaryTypeProperty
extends ItemFullProperty('auxC', version = 0, flags) {
	string aux_type;
	template unsigned int(8) aux_subtype[];
		// until the end of the box, the semantics depend on the aux_type value
}
```

Here the `template` keyword is not needed as there is no default value specified (see ISOBMFF spec).
Also do we define the `string` anywhere? I could not find it.

**Comment by cconcolato** [comment]
We define `utf8string` and `utfstring` (for UTF-8 or 16) but not `string`

**Comment by cconcolato** [comment]
We need to fix this issue in the next ongoing amendment.

**Comment by cconcolato** [comment]
We replace `string` with `utf8string` and remove the keyword `template`
