### ISSUE TITLE
Typo in 14496-12:2022 - MetadataSampleEntry

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#89]
In Section 12.9.4 "Sample entry format", the syntax for `BoxedMetadataSampleEntry` requires that it `extends MetadataSampleEntry ('mebx') {....}`.

There is no `MetadataSampleEntry` that I can find. I think this is a typo for `MetaDataSampleEntry` per section 12.3.3.2.

**Comment by stschr** [comment]
Thank you, @bradh 
I can confirm this as a simple typo.

**Comment by mhannuksela** [comment]
Thanks for reporting the bug. This has been fixed in the 2nd DIS of ISOBMFF 8th Edition. Closing the issue.
