### ISSUE TITLE
ISOBMFF Duplicate file structure clauses

### ISSUE THREAD

**Issue by dwsinger** [MPEGGroup/FileFormat#9]
Subclauses 4.1 and 6.1.1 have the same name and discuss the same aspects. Additionally 5.2 also talks about File Structure, as well as Annex A.
This is confusing and error prone as for instance the notion of "File-level Box" is defined in 4.1 but it is not related to the notion of "presentation file" in 6.1.2.
We recommend merging 4.1 and 6.1.1 keeping only normative text and definitions and moving non-normative text to Annex A.

**Comment by dwsinger** [comment]
4.1 File structure
is about files being sequences of objects

6.1.1 Referencing external data
and is about the ability to reference media in other files.

I don't get this. Close with no action?

**Comment by cconcolato** [comment]
Section 4 is actually defining things except for 4.1
- 4.1 talks about the fact that data is in boxes; about the file type box and about top level boxes
- 4.2 talks about the concept box
- 4.3 is the file type box

Section 5 is about design considerations, but not specifying anything.

Section 6 is specifying things.

I wonder if we could move Section 5 into an Annex, along with 4.1 and start with technical contents: box, ftyp, ...

**Comment by dwsinger** [comment]
Yes, the entire introductory material, explanation of the file format, and so on, needs a massive re-write. It should be in one annex.

**Comment by dwsinger** [comment]
we have a problem that 7th edition 4.2 and 6.2.1 are both called "object structure"; the first clause defines objects (boxes) and the second what objects (boxes) are used to make a movie

**Comment by dwsinger** [comment]
duplicate of #10 closing
