### ISSUE TITLE
thmb item reference in track reference section

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#91]
In 8.3.3.3, on track references, it says

> 
> 'thmb':
> — this track contains thumbnail images for the referenced track. A thumbnail track shall not be linked to another thumbnail track with the 'thmb' item reference.

I think that should be "...with the `thmb` track reference" (not item reference - which looks like a copy-n-paste from HEIF).

**Comment by mhannuksela** [comment]
Thanks, the comment is valid.
The draft 8th Edition text fixes this as follows:

> `'thmb'`	   this track contains thumbnail images for the referenced track. A thumbnail track shall not be linked to another thumbnail track with the `'thmb'` track reference.

**Comment by cconcolato** [comment]
Closing the issue as it is fixed in the 8th edition. Reopen if needed.
