### ISSUE TITLE
Entity Groups require version and flags, but are not specified

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#93]
In ISO/IEC 14496-12:2022 Section 8.18.3.2, the syntax for `EntityToGroupBox` requires a `grouping_type`, `version` and `flags`.

```
aligned(8) class EntityToGroupBox(grouping_type, version, flags) extends FullBox(grouping_type, version, flags) { ...}
```

However most of the concrete instances I checked (`aebr`, `afbr`, `albc`, `altr`, `brst`, `dobr`, `eqiv`, `favc`, `fobr`,  `iaug`, `oval`, `ovbg`, `pano`, `slid`, `ster`, `tsyn`, `vipo`, `vvcb`, `wbbr`, ) do not specify the version or flags. The `oval` and `ovbg` examples (OMAF) are particularly weird.

There are examples that do (`acgl`, `amgl`, `opeg`, `swtk` - which is all of the grouping_types from 14496-15, except `vvcb`).

Also, I didn't check `eply` or `swpc` from V3C-SYS.

Suggest adding some default values to either the syntax for `EntityToGroupBox` (not sure if template is valid there), or adding some explanatory / note text, or both. Perhaps something like "Unless specified otherwise for a particular `grouping_type`, the `version` and `flags` are 0."

**Comment by mhannuksela** [comment]
Thanks for reporting the issue. In the 2nd DIS of ISOBMFF 8th Edition, subclause 8.18.3.3, the use of `version` and `flags` of the `EntityToGroupBox` has been specified as follows:

> `version` shall be 0 unless defined otherwise for the `grouping_type`. Any values of `flags` such that (`flags` & 0x000FFF) is not equal to 0 are reserved. The values of `flags` shall be such that (`flags` & 0xFFF000) is equal to 0 unless defined otherwise for the `grouping_type`.

**Comment by cconcolato** [comment]
Closing this issue which seems to be addressed. Reopen if needed.
