### ISSUE TITLE
On item_name being a relative URL

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/FileFormat#94]
I see this text in the ISOBMFF spec in the definition of the Item Information box `iinf`.

> The `item_name` shall be a valid URL (e.g. a simple name, or path name) and shall not be an absolute URL.

semantics say:

> `item_name` is the symbolic name of the item (source file for file delivery transmissions).

To me it feels a bit confusing as the syntax element refers to a name and not a relative URL. Do implementations out there follow the shall in the definition? Is for example `HEVC Image` or an empty string considered a valid URL?

**Comment by bradh** [comment]
I just grep'd (ack'd) the file format conformance samples for HEIF - none of those look like URLs. A quick check of libheif and libavif-container suggests that both of those are just treating it as a string.  So, it feels like the `item_name` should  just be a descriptive string.

However comparing this to the 2015 version of 14496-12 (5th ed.), it has been added to the 2022 version (7th Ed). I don't have the 6th edition to check where. That looks like it is to support the special-case interpretation added to 8.11.9 where the `item_name` gets used as a relative URL ("if not empty"). So I assume someone wanted it to be a URL (or empty), and that MPEG agreed to the breaking change between Ed 5 and Ed 7 somewhere.

**Comment by leo-barnes** [comment]
I don't think I've seen **any** HEIF file where the item name is a URL. It's either the empty string or some kind of descriptive string of what the image is or who created it.

If this is a recent change, we should really have it reverted since it doesn't conform to reality.

**Comment by leo-barnes** [comment]
Hmmm... It's really weird to require writers to put the name/path name in the `infe`. What are you supposed to do if the file is renamed?

**Comment by mhannuksela** [comment]
The requirement on `item_name` being a URL appeared in the 6th Edition (14496-12:2020) but not was present before that. I could not find quickly why it was added.

**Comment by cconcolato** [comment]
In conversation with the group, it was mentioned that:
- one use case for item_name is to be able to embed resources like HTML pointing to other resources like PNG, and have the URL in the HTML be exactly the item_name, to facilitate navigation
- it seems that implementations have been using free-form text or empty text. Can these be considered relative URLs, or do we need to mention URL-escaping of spaces or special treatment for the empty case.

**Comment by podborski** [comment]
In the WD, can be closed
