### ISSUE TITLE
Syntax for MovieFragmentRandomAccessBox (mfro)

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#96]
ISO/IEC 14496-12 Section 8.8.11.2 has syntax statement:

```
aligned(8) class MovieFragmentRandomAccessOffsetBox
extends FullBox('mfro', version, 0) {
...
}
```

However there is no version dependency, nor any identification of allowed versions.

Suggest:

```
aligned(8) class MovieFragmentRandomAccessOffsetBox
extends FullBox('mfro', 0, 0) {
...
}
```

**Comment by mhannuksela** [comment]
Thanks for reporting the bug. The issue and the fix have been included in the ISOBMFF defect report in the April 2024 MPEG meeting and will eventually be corrected in a future amendment or edition of ISOBMFF. Closing the issue here.
