### ISSUE TITLE
[NALU] OperatingPointRecord editorial issue

### ISSUE THREAD

**Issue by bradh** [MPEGGroup/FileFormat#98]
(Edit to fix typo)

In the syntax for `OperatingPointRecord` (ISO/IEC 14496-15:2022 Section 9.6.2.2), the loop for operating points is `for (i=0; i<num_operating_points) ...`.  I think that should be `for (i=0; i<num_operating_points; i++) ...`

(I do not have permission to add labels, so added it to the title - if adding a label, please edit that).

**Comment by leo-barnes** [comment]
Nit:
```diff
- for (i=0; i<num_operating_points, i++)
+ for (i=0; i<num_operating_points; i++)
```

**Comment by bradh** [comment]
> Nit:
> 
> ```diff
> - for (i=0; i<num_operating_points, i++)
> + for (i=0; i<num_operating_points; i++)
> ```

Indeed. Updated the report.

**Comment by mhannuksela** [comment]
This bug has already been fixed in 14496-15 7th Edition. Closing the issue.
